### ISSUE TITLE
Proposal to Add "Get Transaction" Feature

### ISSUE THREAD

**Issue by developerkunal** [thirdweb-dev/engine#220]
#### Context

Our project currently supports the functionality to send raw transactions. To enhance our users' experience and provide them with a more comprehensive feature set, we propose the addition of a "Get Transaction" feature.

#### Rationale

- **Improved User Experience:** This feature would allow users to retrieve detailed information about transactions they have initiated, which is crucial for monitoring and troubleshooting.
- **Enhanced Debugging:** Developers and administrators will benefit from this feature when diagnosing issues with specific transactions. Being able to query transaction details by `chainId` and `queueId` is a valuable debugging tool.
- **Consistency:** The "Get Transaction" feature aligns with industry standards and practices, making our application more user-friendly.

### Proposed Solution

We suggest implementing an API endpoint that accepts `chainId` and `queueId` as parameters, as this would be a simple and intuitive way for users to retrieve transaction details.

### Implementation Details

We can use the existing database structure to fetch transaction details based on the provided `chainId` and `queueId`. The response should follow our standard response schema.

### Example Use Case

A user can make a `GET` request to `/backend-wallet/:chain/get-transaction/:queueId`, and the system would return transaction details if they exist in the database.

### Potential Impact

This feature would positively impact our users and may attract more users to our platform due to the enhanced functionality.

### Next Steps

1. Define the specific route and endpoint for this feature.
2. Implement the route handler and database queries.
3. Update the API documentation to include information about this new feature.

**Comment by farhanW3** [comment]
Hi @developerkunal, we do have an end-point `/transaction/status/:queueId` which gives you a detailed information on the transaction.

<img width="1457" alt="image" src="https://github.com/thirdweb-dev/engine/assets/132962163/a3105855-e987-4953-9ed1-692ea2493cf6">

**Comment by developerkunal** [comment]
Thanks
