### ISSUE TITLE
Engine wrong set up https in Dockerfile

### ISSUE THREAD

**Issue by cauta** [thirdweb-dev/engine#362]
i have problem when enable https. the engine api throw error that there is no key and cert file in `/app/src/https`

i found the problem come from https set up at [Dockerfile](https://github.com/thirdweb-dev/engine/blob/3f8d9bb24c7d40ad6332715e172a7e5db1910259/Dockerfile#L26C10-L26C13) 
it should be 
```
WORKDIR /app/src/https
```

More info about error:

![image](https://github.com/thirdweb-dev/engine/assets/15400058/b3c85c95-45b0-4889-bb09-70597cab5e46)

@warengonzaga

**Comment by farhanW3** [comment]
this is when you are running it locally with Docker I believe. Will fix it. Thanks

**Comment by farhanW3** [comment]
Fixed, in this [PR](https://github.com/thirdweb-dev/engine/pull/363)

**Comment by farhanW3** [comment]
Fixed, in this [PR](https://github.com/thirdweb-dev/engine/pull/363)
