### ISSUE TITLE
The error occurred when running Docker for the Prisma database section regarding triggers.

### ISSUE THREAD

**Issue by Kinghood15** [thirdweb-dev/engine#365]
I am having an issue creating a Prisma database when running the application on Docker. Specifically, when merging code to the main branch and building the Docker image, the database creation step fails with an error. I have tried various solutions but have not been able to resolve the problem.
@farhanW3 
![image](https://github.com/thirdweb-dev/engine/assets/74972851/0a90b8be-f2e2-49de-a57f-80e167ffb616)

**Comment by farhanW3** [comment]
I think, you are running with `NODE_ENV` set to `production`, change it to `development`

If you are not developing and would like to play with it, I would recommend to use either `latest`, `nightly` or any other version. But, if running for development purpose, update the `NODE_ENV` to `development`

let me know, if this fixes it

**Comment by farhanW3** [comment]
@Kinghood15 let me know if this worked for you?

**Comment by Kinghood15** [comment]
@farhanW3 I haven't tried your method yet, but I have corrected it in the docker compose file. Thank you for your help
