### ISSUE TITLE
Ignore self-sign ssl certificate from engine-sdk

### ISSUE THREAD

**Issue by warengonzaga** [thirdweb-dev/engine#383]
Originally from community on our [Discord server](https://discord.com/channels/834227967404146718/1181437028961886349).

> I already install thirdweb engine to my cloud server with a public ip address
>
> first, i would like to use the thirdweb dashboard to manage my engine. so i enable ssl flag and work so well.
>
> but, another thing, when i tried to use engine sdk (especially the template "Smart Account Engine Sessions Demo")  from localhost. 
>
> i can not connect or retrieve data from engine, because it's self signed certificate.
so, i would like to know that, are there any solutions that i can ignore ssl from engine-sdk, so i can use both thirdweb-dashboard and develop from my localhost
thanks for replying me. Looking forward to hearing you soon

Can you check this @farhanW3? Thanks!

**Comment by farhanW3** [comment]
hi @warengonzaga 

Few things & questions:

1. if the user is hosting on a cloud, they shouldn't need to turn on the HTTPS flag. Just run as is. The `ENABLE_HTTPS` env variable is to be used when running the docker image locally.
2. Can I get a link to the example mentioned?

**Comment by farhanW3** [comment]
@warengonzaga 

any updates here. else will close this issue?
