### ISSUE TITLE
Documented CHAIN_OVERRIDES .env variable doesn't take effect

### ISSUE THREAD

**Issue by gregfromstl** [thirdweb-dev/engine#413]
The user guide specifies a `CHAIN_OVERRIDES` .env option to override the default chain configurations, but that variable isn't used anywhere.

**Comment by farhanW3** [comment]
hi @gregfromstl 

thank you for reporting this. We have removed the ENV variable and made an end-point on Engine under `configuration` which helps with the same.

End-point: `/configuration/chains`
Method(s): GET & POST.

I will update the docs to reflect this change.

**Comment by bennettl** [comment]
@farhanW3 can you point to where in the docs this is?

**Comment by farhanW3** [comment]
@bennettl Here, [How do I customize my RPC?](https://portal.thirdweb.com/engine/faq#how-do-i-customize-my-rpc)
