### ISSUE TITLE
`merkleRootHash` gets ignored when calling `erc1155.setClaimConditions`

### ISSUE THREAD

**Issue by igorroncevic** [thirdweb-dev/engine#457]
Whatever I set as a value for the `merkleRootHash`, it gets set as `0x00...`, but everything else is set properly.

Here's how I'm calling `setClaimConditions`:
```
await engine.erc1155.setClaimConditions(
    "11155111",
    "0x0E3cD0Ddb82B0670c2F396E7e4e5A25161a8cDbD",
    process.env.BACKEND_WALLET,
    {
      tokenId: '0',
      claimConditionInputs: [
        {
          maxClaimableSupply: '10000',
          maxClaimablePerWallet: '5',
          startTime: 1710849504000,
          merkleRootHash: '0xc817d2930f033ad922cf5de2994bd79d2bf0cd9dfb1abb509f36f8927e881882'
        }
      ]
    }
);
```

And this is what I get as an output from `getActiveClaimCondition`:
```
{
  maxClaimableSupply: '10000',
  startTime: '2024-03-19T11:58:24.000Z',
  price: '0',
  currencyAddress: '0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE',
  maxClaimablePerWallet: '5',
  waitInSeconds: '0',
  merkleRootHash: '0x0000000000000000000000000000000000000000000000000000000000000000',
  availableSupply: '10000',
  currentMintSupply: '0',
  currencyMetadata: {
    name: 'Sepolia Ether',
    symbol: 'ETH',
    decimals: 18,
    value: '0',
    displayValue: '0.0'
  }
}
```

Here's the transaction on the Sepolia block explorer: https://sepolia.etherscan.io/tx/0xf6000a59a20e108f4c25bf8255c2183fc58fe786f3049167b416be62c2b943ed

**Comment by farhanW3** [comment]
hey @igorroncevic 

Thanks for the report. Will check and get back to you on this.

**Comment by igorroncevic** [comment]
> hey @igorroncevic
> 
> Thanks for the report. Will check and get back to you on this.

Hey @farhanW3, I've now switched to using the SDK and I've figured out that `merkleRootHash` gets updated properly only when the `snapshot` array is provided, therefore it might be due to the fact that the `merkleRootHash` parameter is ignored and the hash is being computed from the `snapshot` itself. 

This might be an intended behaviour, but I found it out of sheer luck, since the documentation on allowlists is pretty scarce.

**Comment by farhanW3** [comment]
thanks for the update.
