### ISSUE TITLE
Engine API not working

### ISSUE THREAD

**Issue by SagarKarmoker** [thirdweb-dev/engine#522]
Unable to render this definition
The provided definition does not specify a valid version field.

Please indicate a valid Swagger or OpenAPI version field. Supported version fields are swagger: "2.0" and those that match openapi: 3.x.y (for example, openapi: 3.1.0).

![image](https://github.com/thirdweb-dev/engine/assets/98447327/23b10e48-af4a-4dbc-a730-647fb40c1955)
![image](https://github.com/thirdweb-dev/engine/assets/98447327/1107a24b-282c-40d3-a26d-53d6af618d1b)

**Comment by farhanW3** [comment]
hi @SagarKarmoker 

In the image you pasted the first `key` is `"openapi": "3.0.3"`.

Can you share more details:

- which Engine version you are using?
- Seems like you are running it `locally` & using `ngrok`.
- Can you try setting the `ENABLE_HTTPS` to `true` when running locally and see if you are able to connect to it via dashboard. 

In the meantime I will try it with `ngrok` and check it.

**Comment by farhanW3** [comment]
@SagarKarmoker 

are you still facing this issue?

**Comment by farhanW3** [comment]
I @SagarKarmoker 

I tried the same setup and everything seemed to work for me. Can you confirm the below:

1. On your `.env` file the make sure to comment/remove the variable `ENABLE_HTTPS` other it gives errors..

**Comment by SagarKarmoker** [comment]
@farhanW3 I am using docker where can I make these .env changes?

**Comment by farhanW3** [comment]
@SagarKarmoker I see what is happening. Will look into a fix for it

**Comment by farhanW3** [comment]
@SagarKarmoker 

we have pushed an update on the Dashboard. If you can give it a try.

**Comment by SagarKarmoker** [comment]
Sure I will do that. Let's give you an update as soon as possible

**Comment by SagarKarmoker** [comment]
Now working fine. Thanks dude
