### ISSUE TITLE
TxSimulate 400

### ISSUE THREAD

**Issue by dcapitator** [thirdweb-dev/engine#600]
while debugging manually TXs on my self hosted engine from engine dashboard, I found out that Simulation of TxRaw isn't going right !

`{
  "toAddress": "0xfff9976782d46cc05630d1f6ebab18b2324d6b14",
"data":"0x095ea7b30000000000000000000000003bfa4769fb09eefc5a80d6e87c3b9c650f7ae48e000000000000000000000000000000000000007e37be2022c0914b2680000000",
  "value": "0x00",
  "txOverrides": {
    "gas": "70000"
  }
}`

This is an approval TxRaw to spend WETH. The backend wallet has gas. 
On simulation i get the error :
`{
  "error": {
    "message": "Transaction simulation failed with reason: data out-of-bounds",
    "code": "BAD_REQUEST",
    "statusCode": 400
  }
}`

But Processing the TxRaw without simulation succeeded :

https://sepolia.etherscan.io/tx/0x4f830e567627b0e0ad2534688831a2dd891c9075aca6e7c57b1d9fe56cf4aa77

**Comment by arcoraven** [comment]
Thanks for the report. We'll take a look with the details you provided. Please let us know if you're able to narrow down more specific flows that trigger this error.
